begin;

create extension if not exists pgcrypto;

create type public.load_basis as enum (
  'external_total',
  'per_dumbbell',
  'added_bodyweight',
  'bodyweight_only',
  'assistance',
  'repetition_only'
);

create type public.cycle_status as enum ('planned', 'active', 'completed', 'abandoned');
create type public.scheduled_workout_status as enum ('queued', 'active', 'completed', 'partial', 'skipped');
create type public.session_status as enum ('active', 'completed', 'partial', 'abandoned');
create type public.session_exercise_status as enum ('pending', 'active', 'completed', 'partial', 'skipped');
create type public.exercise_set_status as enum ('draft', 'completed', 'skipped', 'deleted');

create function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  timezone text not null default 'America/Chicago',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_length check (display_name is null or char_length(display_name) <= 120),
  constraint profiles_timezone_present check (char_length(timezone) between 1 and 100)
);

create table public.user_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  weight_unit text not null default 'lb' check (weight_unit = 'lb'),
  default_increment_tenths_lb integer not null default 25 check (default_increment_tenths_lb > 0),
  theme text not null default 'system' check (theme in ('system', 'light', 'dark')),
  dark_mode_bias boolean not null default true,
  reduced_motion_override text check (reduced_motion_override in ('system', 'reduce', 'no-preference')),
  timer_sound boolean not null default false,
  timer_vibration boolean not null default true,
  muscle_set_reference_tenths integer not null default 150 check (muscle_set_reference_tenths > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.muscle_groups (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  display_order smallint not null unique,
  constraint muscle_groups_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.exercises (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references public.profiles(id) on delete cascade,
  slug text,
  name text not null,
  equipment_type text not null,
  load_basis public.load_basis not null,
  default_rep_min smallint check (default_rep_min > 0),
  default_rep_max smallint check (default_rep_max > 0),
  default_increment_tenths_lb integer check (default_increment_tenths_lb > 0),
  minimum_load_tenths_lb integer check (minimum_load_tenths_lb >= 0),
  maximum_load_tenths_lb integer check (maximum_load_tenths_lb >= 0),
  valid_loads_tenths_lb integer[],
  default_rest_seconds integer check (default_rest_seconds between 30 and 600),
  guidance text[] not null default '{}',
  technique_check text check (technique_check in ('squat', 'rdl')),
  is_curated boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, owner_user_id),
  constraint exercises_name_present check (char_length(trim(name)) between 1 and 120),
  constraint exercises_slug_format check (slug is null or slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint exercises_rep_range check (
    default_rep_min is null or default_rep_max is null or default_rep_min <= default_rep_max
  ),
  constraint exercises_load_range check (
    minimum_load_tenths_lb is null or maximum_load_tenths_lb is null
    or minimum_load_tenths_lb <= maximum_load_tenths_lb
  ),
  constraint exercises_curated_ownership check (
    (is_curated and owner_user_id is null) or (not is_curated and owner_user_id is not null)
  )
);

create unique index exercises_curated_slug_key on public.exercises(slug) where owner_user_id is null;
create unique index exercises_owner_name_key on public.exercises(owner_user_id, lower(name)) where owner_user_id is not null;

create table public.exercise_muscles (
  exercise_id uuid not null references public.exercises(id) on delete cascade,
  muscle_group_id smallint not null references public.muscle_groups(id) on delete restrict,
  owner_user_id uuid references public.profiles(id) on delete cascade,
  contribution_tenths smallint not null check (contribution_tenths in (5, 10)),
  role text not null check (role in ('primary', 'secondary')),
  primary key (exercise_id, muscle_group_id),
  constraint exercise_muscles_role_contribution check (
    (role = 'primary' and contribution_tenths = 10)
    or (role = 'secondary' and contribution_tenths = 5)
  )
);

create table public.exercise_substitutions (
  id uuid primary key default gen_random_uuid(),
  source_exercise_id uuid not null references public.exercises(id) on delete cascade,
  replacement_exercise_id uuid not null references public.exercises(id) on delete cascade,
  owner_user_id uuid references public.profiles(id) on delete cascade,
  compatibility_rank smallint not null default 100 check (compatibility_rank > 0),
  notes text,
  constraint exercise_substitution_distinct check (source_exercise_id <> replacement_exercise_id)
);

create unique index exercise_substitutions_curated_key
on public.exercise_substitutions(source_exercise_id, replacement_exercise_id)
where owner_user_id is null;
create unique index exercise_substitutions_owner_key
on public.exercise_substitutions(source_exercise_id, replacement_exercise_id, owner_user_id)
where owner_user_id is not null;

create table public.programs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  source_format_version text not null default '1.0',
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  constraint programs_name_present check (char_length(trim(name)) between 1 and 120)
);

create table public.program_revisions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  program_id uuid not null,
  revision_number integer not null check (revision_number > 0),
  source_json jsonb not null,
  source_checksum text not null,
  week_count smallint not null check (week_count between 1 and 52),
  workouts_per_week smallint not null check (workouts_per_week between 1 and 7),
  status text not null default 'draft' check (status in ('draft', 'validated', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (program_id, revision_number),
  foreign key (program_id, user_id) references public.programs(id, user_id) on delete cascade,
  constraint program_revision_publication check (
    (status = 'published' and published_at is not null) or status <> 'published'
  )
);

create table public.program_week_rules (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  program_revision_id uuid not null,
  week_number smallint not null check (week_number between 1 and 52),
  phase_name text not null,
  target_rir_min smallint not null check (target_rir_min between 0 and 6),
  target_rir_max smallint not null check (target_rir_max between 0 and 6),
  is_deload boolean not null default false,
  load_reduction_min_percent smallint check (load_reduction_min_percent between 0 and 100),
  load_reduction_max_percent smallint check (load_reduction_max_percent between 0 and 100),
  guidance text,
  unique (program_revision_id, week_number),
  foreign key (program_revision_id, user_id) references public.program_revisions(id, user_id) on delete cascade,
  constraint program_week_rir_range check (target_rir_min <= target_rir_max),
  constraint program_week_load_reduction_range check (
    load_reduction_min_percent is null or load_reduction_max_percent is null
    or load_reduction_min_percent <= load_reduction_max_percent
  )
);

create table public.program_set_rules (
  user_id uuid not null references public.profiles(id) on delete cascade,
  program_revision_id uuid not null,
  week_number smallint not null check (week_number between 1 and 52),
  peak_sets smallint not null check (peak_sets in (2, 3, 4)),
  prescribed_sets smallint not null check (prescribed_sets between 1 and 4),
  optional_additional_sets smallint not null default 0 check (optional_additional_sets between 0 and 1),
  primary key (program_revision_id, week_number, peak_sets),
  foreign key (program_revision_id, user_id) references public.program_revisions(id, user_id) on delete cascade,
  constraint program_set_rule_ceiling check (prescribed_sets + optional_additional_sets <= peak_sets)
);

create table public.workout_templates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  program_revision_id uuid not null,
  sequence_in_week smallint not null check (sequence_in_week between 1 and 7),
  name text not null,
  original_day_label text,
  guidance text,
  unique (id, user_id),
  unique (program_revision_id, sequence_in_week),
  foreign key (program_revision_id, user_id) references public.program_revisions(id, user_id) on delete cascade
);

create table public.workout_template_exercises (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  workout_template_id uuid not null,
  exercise_id uuid not null references public.exercises(id) on delete restrict,
  sequence_number smallint not null check (sequence_number > 0),
  peak_sets smallint not null check (peak_sets in (2, 3, 4)),
  rep_min smallint not null check (rep_min > 0),
  rep_max smallint not null check (rep_max > 0),
  increment_tenths_lb integer check (increment_tenths_lb > 0),
  rest_seconds integer check (rest_seconds between 30 and 600),
  guidance text[] not null default '{}',
  technique_check text check (technique_check in ('squat', 'rdl')),
  unique (workout_template_id, sequence_number),
  foreign key (workout_template_id, user_id) references public.workout_templates(id, user_id) on delete cascade,
  constraint workout_template_exercise_rep_range check (rep_min <= rep_max)
);

create table public.program_cycles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  program_revision_id uuid not null,
  name text not null,
  starts_on date not null,
  timezone text not null,
  status public.cycle_status not null default 'planned',
  current_week_number smallint not null default 1 check (current_week_number between 1 and 52),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (program_revision_id, user_id) references public.program_revisions(id, user_id) on delete restrict
);

create unique index one_active_cycle_per_user on public.program_cycles(user_id) where status = 'active';

create table public.scheduled_workouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  cycle_id uuid not null,
  program_week_number smallint not null check (program_week_number between 1 and 52),
  template_id uuid not null,
  sequence_in_cycle integer not null check (sequence_in_cycle > 0),
  original_scheduled_date date not null,
  current_scheduled_date date not null,
  status public.scheduled_workout_status not null default 'queued',
  rollover_count integer not null default 0 check (rollover_count >= 0),
  skipped_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (cycle_id, sequence_in_cycle),
  foreign key (cycle_id, user_id) references public.program_cycles(id, user_id) on delete cascade,
  foreign key (template_id, user_id) references public.workout_templates(id, user_id) on delete restrict,
  constraint scheduled_workout_skip_reason check (status <> 'skipped' or skipped_reason is not null)
);

create index scheduled_workouts_queue_idx on public.scheduled_workouts(user_id, status, sequence_in_cycle);
create index scheduled_workouts_week_idx on public.scheduled_workouts(cycle_id, program_week_number);
create index scheduled_workouts_date_idx on public.scheduled_workouts(user_id, current_scheduled_date);

create table public.workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  scheduled_workout_id uuid not null,
  cycle_id uuid not null,
  program_revision_id uuid not null,
  program_week_number smallint not null,
  template_name_snapshot text not null,
  phase_name_snapshot text not null,
  target_rir_min_snapshot smallint not null check (target_rir_min_snapshot between 0 and 6),
  target_rir_max_snapshot smallint not null check (target_rir_max_snapshot between 0 and 6),
  status public.session_status not null default 'active',
  started_at timestamptz not null,
  finished_at timestamptz,
  performed_local_date date not null,
  timezone text not null,
  bodyweight_tenths_lb integer check (bodyweight_tenths_lb > 0),
  energy_rating smallint check (energy_rating between 1 and 5),
  discomfort_level text check (discomfort_level in ('none', 'mild', 'moderate', 'severe')),
  discomfort_notes text,
  notes text,
  next_time_adjustment text,
  reduced_volume_reason text,
  revision integer not null default 1 check (revision > 0),
  client_created_at timestamptz not null,
  server_created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (scheduled_workout_id),
  foreign key (scheduled_workout_id, user_id) references public.scheduled_workouts(id, user_id) on delete restrict,
  foreign key (cycle_id, user_id) references public.program_cycles(id, user_id) on delete restrict,
  foreign key (program_revision_id, user_id) references public.program_revisions(id, user_id) on delete restrict,
  constraint workout_session_rir_range check (target_rir_min_snapshot <= target_rir_max_snapshot),
  constraint workout_session_finished_state check (
    (status = 'active' and finished_at is null) or (status <> 'active' and finished_at is not null)
  )
);

create unique index one_active_session_per_user on public.workout_sessions(user_id) where status = 'active';
create index workout_sessions_history_idx on public.workout_sessions(user_id, finished_at desc);

create table public.session_exercises (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid not null,
  sequence_number smallint not null check (sequence_number > 0),
  prescribed_exercise_id uuid not null references public.exercises(id) on delete restrict,
  performed_exercise_id uuid not null references public.exercises(id) on delete restrict,
  replacement_reason text,
  exercise_name_snapshot text not null,
  load_basis_snapshot public.load_basis not null,
  rep_min_snapshot smallint not null check (rep_min_snapshot > 0),
  rep_max_snapshot smallint not null check (rep_max_snapshot > 0),
  prescribed_sets_snapshot smallint not null check (prescribed_sets_snapshot between 1 and 4),
  optional_sets_snapshot smallint not null default 0 check (optional_sets_snapshot between 0 and 1),
  increment_tenths_lb_snapshot integer not null check (increment_tenths_lb_snapshot > 0),
  rest_seconds_snapshot integer not null check (rest_seconds_snapshot between 30 and 600),
  guidance_snapshot text[] not null default '{}',
  status public.session_exercise_status not null default 'pending',
  technique_compromised boolean,
  pain_flag boolean,
  fatigue_flag boolean,
  limiting_factor text check (limiting_factor in ('cardiovascular', 'muscular', 'mixed', 'unsure')),
  stimulus_rating smallint check (stimulus_rating between 1 and 5),
  lower_back_fatigue_rating smallint check (lower_back_fatigue_rating between 1 and 5),
  exercise_notes text,
  progression_decision text check (progression_decision in ('increase', 'maintain', 'review_reduce', 'override')),
  progression_override_load_tenths_lb integer check (progression_override_load_tenths_lb >= 0),
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (session_id, sequence_number),
  foreign key (session_id, user_id) references public.workout_sessions(id, user_id) on delete cascade,
  constraint session_exercise_rep_range check (rep_min_snapshot <= rep_max_snapshot),
  constraint session_exercise_replacement_reason check (
    prescribed_exercise_id = performed_exercise_id or replacement_reason is not null
  )
);

create index session_exercises_history_idx on public.session_exercises(user_id, performed_exercise_id, created_at desc);

create table public.exercise_sets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_exercise_id uuid not null,
  set_number smallint not null check (set_number > 0),
  set_kind text not null default 'working' check (set_kind in ('working', 'optional', 'warmup')),
  status public.exercise_set_status not null default 'draft',
  load_mode public.load_basis not null,
  load_tenths_lb integer check (load_tenths_lb >= 0),
  reps smallint check (reps > 0),
  target_rir_min_snapshot smallint not null check (target_rir_min_snapshot between 0 and 6),
  target_rir_max_snapshot smallint not null check (target_rir_max_snapshot between 0 and 6),
  rir_on_target boolean,
  actual_rir smallint check (actual_rir between 0 and 6),
  actual_rir_over_six boolean not null default false,
  actual_rir_unsure boolean not null default false,
  notes text,
  completed_at timestamptz,
  client_mutation_id uuid not null,
  revision integer not null default 1 check (revision > 0),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_exercise_id, set_number),
  unique (client_mutation_id),
  foreign key (session_exercise_id, user_id) references public.session_exercises(id, user_id) on delete cascade,
  constraint exercise_set_rir_range check (target_rir_min_snapshot <= target_rir_max_snapshot),
  constraint exercise_set_completed_fields check (
    status <> 'completed' or (reps is not null and completed_at is not null and rir_on_target is not null)
  ),
  constraint exercise_set_load_semantics check (
    (load_mode in ('bodyweight_only', 'repetition_only') and load_tenths_lb is null)
    or (load_mode not in ('bodyweight_only', 'repetition_only') and load_tenths_lb is not null)
  ),
  constraint exercise_set_actual_rir_exclusive check (
    num_nonnulls(actual_rir, nullif(actual_rir_over_six, false), nullif(actual_rir_unsure, false)) <= 1
  ),
  constraint exercise_set_deleted_state check (
    (status = 'deleted' and deleted_at is not null) or (status <> 'deleted' and deleted_at is null)
  )
);

create index exercise_sets_history_idx on public.exercise_sets(user_id, completed_at desc);
create index exercise_sets_status_idx on public.exercise_sets(user_id, status);

create table public.edit_audit_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  entity_type text not null,
  entity_id uuid not null,
  action text not null,
  before_values jsonb,
  after_values jsonb,
  reason text,
  client_mutation_id uuid not null unique,
  created_at timestamptz not null default now()
);

create index edit_audit_entity_idx on public.edit_audit_events(user_id, entity_type, entity_id, created_at desc);

create table public.weekly_checkins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  cycle_id uuid not null,
  program_week_number smallint not null check (program_week_number between 1 and 52),
  overall_recovery smallint check (overall_recovery between 1 and 5),
  average_sleep_hours_tenths smallint check (average_sleep_hours_tenths between 0 and 240),
  energy smallint check (energy between 1 and 5),
  overall_soreness smallint check (overall_soreness between 1 and 5),
  joint_discomfort text check (joint_discomfort in ('none', 'mild', 'moderate', 'severe')),
  joint_discomfort_notes text,
  motivation smallint check (motivation between 1 and 5),
  strongest_lift_session_exercise_id uuid references public.session_exercises(id) on delete set null,
  worst_exercise_id uuid references public.exercises(id) on delete set null,
  biggest_improvement text,
  recovery_factors text,
  next_week_actions text[] not null default '{}',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (cycle_id, program_week_number),
  foreign key (cycle_id, user_id) references public.program_cycles(id, user_id) on delete cascade
);

create table public.weekly_muscle_recovery (
  weekly_checkin_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  muscle_group_id smallint not null references public.muscle_groups(id) on delete restrict,
  recovery_rating smallint check (recovery_rating between 1 and 5),
  notes text,
  primary key (weekly_checkin_id, muscle_group_id),
  foreign key (weekly_checkin_id, user_id) references public.weekly_checkins(id, user_id) on delete cascade
);

create table public.body_metrics (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  measured_at timestamptz not null,
  bodyweight_tenths_lb integer not null check (bodyweight_tenths_lb > 0),
  source text not null check (source in ('session', 'manual', 'checkin')),
  source_id uuid,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index body_metrics_history_idx on public.body_metrics(user_id, measured_at desc);

create function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id);
  insert into public.user_preferences (user_id) values (new.id);
  return new;
end;
$$;

create function public.prevent_published_program_revision_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if old.status = 'published' then
    raise exception 'Published program revisions are immutable';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger create_profile_after_auth_user
after insert on auth.users
for each row execute function public.create_profile_for_new_user();

create trigger prevent_published_program_revision_update
before update or delete on public.program_revisions
for each row execute function public.prevent_published_program_revision_change();

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger user_preferences_set_updated_at before update on public.user_preferences
for each row execute function public.set_updated_at();
create trigger exercises_set_updated_at before update on public.exercises
for each row execute function public.set_updated_at();
create trigger programs_set_updated_at before update on public.programs
for each row execute function public.set_updated_at();
create trigger program_revisions_set_updated_at before update on public.program_revisions
for each row execute function public.set_updated_at();
create trigger program_cycles_set_updated_at before update on public.program_cycles
for each row execute function public.set_updated_at();
create trigger scheduled_workouts_set_updated_at before update on public.scheduled_workouts
for each row execute function public.set_updated_at();
create trigger workout_sessions_set_updated_at before update on public.workout_sessions
for each row execute function public.set_updated_at();
create trigger session_exercises_set_updated_at before update on public.session_exercises
for each row execute function public.set_updated_at();
create trigger exercise_sets_set_updated_at before update on public.exercise_sets
for each row execute function public.set_updated_at();
create trigger weekly_checkins_set_updated_at before update on public.weekly_checkins
for each row execute function public.set_updated_at();
create trigger body_metrics_set_updated_at before update on public.body_metrics
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.user_preferences enable row level security;
alter table public.muscle_groups enable row level security;
alter table public.exercises enable row level security;
alter table public.exercise_muscles enable row level security;
alter table public.exercise_substitutions enable row level security;
alter table public.programs enable row level security;
alter table public.program_revisions enable row level security;
alter table public.program_week_rules enable row level security;
alter table public.program_set_rules enable row level security;
alter table public.workout_templates enable row level security;
alter table public.workout_template_exercises enable row level security;
alter table public.program_cycles enable row level security;
alter table public.scheduled_workouts enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.session_exercises enable row level security;
alter table public.exercise_sets enable row level security;
alter table public.edit_audit_events enable row level security;
alter table public.weekly_checkins enable row level security;
alter table public.weekly_muscle_recovery enable row level security;
alter table public.body_metrics enable row level security;

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
grant usage on schema public to authenticated;
grant select on public.muscle_groups to authenticated;
grant select on public.exercises, public.exercise_muscles, public.exercise_substitutions to authenticated;
grant insert, update on public.exercises, public.exercise_muscles, public.exercise_substitutions to authenticated;
grant select, insert, update on public.profiles, public.user_preferences to authenticated;
grant select, insert, update on public.programs, public.program_revisions, public.program_week_rules,
  public.program_set_rules, public.workout_templates, public.workout_template_exercises, public.program_cycles,
  public.scheduled_workouts, public.workout_sessions, public.session_exercises, public.exercise_sets,
  public.weekly_checkins, public.weekly_muscle_recovery, public.body_metrics to authenticated;
grant select, insert on public.edit_audit_events to authenticated;

create policy profiles_select_own on public.profiles for select to authenticated
using ((select auth.uid()) = id);
create policy profiles_update_own on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy user_preferences_select_own on public.user_preferences for select to authenticated
using ((select auth.uid()) = user_id);
create policy user_preferences_insert_own on public.user_preferences for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy user_preferences_update_own on public.user_preferences for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy muscle_groups_read on public.muscle_groups for select to authenticated using (true);

create policy exercises_read on public.exercises for select to authenticated
using (owner_user_id is null or (select auth.uid()) = owner_user_id);
create policy exercises_insert_custom on public.exercises for insert to authenticated
with check ((select auth.uid()) = owner_user_id and not is_curated);
create policy exercises_update_custom on public.exercises for update to authenticated
using ((select auth.uid()) = owner_user_id and not is_curated)
with check ((select auth.uid()) = owner_user_id and not is_curated);

create policy exercise_muscles_read on public.exercise_muscles for select to authenticated
using (owner_user_id is null or (select auth.uid()) = owner_user_id);
create policy exercise_muscles_insert_own on public.exercise_muscles for insert to authenticated
with check ((select auth.uid()) = owner_user_id);
create policy exercise_muscles_update_own on public.exercise_muscles for update to authenticated
using ((select auth.uid()) = owner_user_id) with check ((select auth.uid()) = owner_user_id);

create policy exercise_substitutions_read on public.exercise_substitutions for select to authenticated
using (owner_user_id is null or (select auth.uid()) = owner_user_id);
create policy exercise_substitutions_insert_own on public.exercise_substitutions for insert to authenticated
with check ((select auth.uid()) = owner_user_id);
create policy exercise_substitutions_update_own on public.exercise_substitutions for update to authenticated
using ((select auth.uid()) = owner_user_id) with check ((select auth.uid()) = owner_user_id);

create policy programs_owner_all on public.programs for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy program_revisions_owner_all on public.program_revisions for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy program_week_rules_owner_all on public.program_week_rules for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy program_set_rules_owner_all on public.program_set_rules for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy workout_templates_owner_all on public.workout_templates for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy workout_template_exercises_owner_all on public.workout_template_exercises for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy program_cycles_owner_all on public.program_cycles for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy scheduled_workouts_owner_all on public.scheduled_workouts for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy workout_sessions_owner_all on public.workout_sessions for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy session_exercises_owner_all on public.session_exercises for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy exercise_sets_owner_all on public.exercise_sets for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy weekly_checkins_owner_all on public.weekly_checkins for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy weekly_muscle_recovery_owner_all on public.weekly_muscle_recovery for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy body_metrics_owner_all on public.body_metrics for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy edit_audit_events_select_own on public.edit_audit_events for select to authenticated
using ((select auth.uid()) = user_id);
create policy edit_audit_events_insert_own on public.edit_audit_events for insert to authenticated
with check ((select auth.uid()) = user_id);

commit;
